apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-mqtt-transport
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
      protocol: TCP
    - port: 8883
      targetPort: 8883
      name: mqtts
---
apiVersion: v1
kind: Service
metadata:
  name: tb-coap-loadbalancer-external
  namespace: thingsboard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-coap-transport
  ports:
    - port: 5683
      targetPort: 5683
      name: coap
      protocol: UDP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: thingsboard
  name: tb-http-loadbalancer-external
spec:
  tls:
    - secretName: ssl-cert-secret
  rules:
    - http:
        paths:
          - path: /api/v1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-http-transport
                port:
                  number: 8080
          - path: /static/rulenode/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-node
                port:
                  number: 8080
          - path: /static/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-node
                port:
                  number: 8080