apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-loadbalancer-external
  namespace: thingsboard
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: ThingsBoardClusterELB=ThingsBoard
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts
---
apiVersion: v1
kind: Service
metadata:
  name: tb-coap-loadbalancer-external
  namespace: thingsboard
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: ThingsBoardClusterELB=ThingsBoardCoap
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-node
  ports:
    - port: 5683
      targetPort: 5683
      name: coap
      protocol: UDP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: thingsboard
  name: tb-http-loadbalancer-external
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
    alb.ingress.kubernetes.io/certificate-arn: ARN_VALUE
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: tb-node
              servicePort: 8080